# Generated by Django 3.1.2 on 2021-03-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmt_user', models.CharField(default='', max_length=100)),
                ('cmt', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
