# Generated by Django 3.1.2 on 2021-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cmt_user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
