# Generated by Django 3.1.2 on 2021-03-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0002_auto_20210304_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cmt',
            new_name='cmt_msg',
        ),
    ]
