# Generated by Django 3.1.2 on 2021-03-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0006_auto_20210305_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_up',
            name='v_user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
