# Generated by Django 3.1.2 on 2021-03-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0007_video_up_v_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cmt_vid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
