# Generated by Django 3.1.2 on 2021-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0008_comment_cmt_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt_vid',
            field=models.IntegerField(default='', max_length=20),
        ),
    ]
