# Generated by Django 3.1.2 on 2021-03-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0009_auto_20210305_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt_vid',
            field=models.IntegerField(default=0),
        ),
    ]
