# Generated by Django 3.1.2 on 2021-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0010_auto_20210305_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_postid', models.ImageField(default='', upload_to='')),
                ('l_user', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
