# Generated by Django 3.1.2 on 2021-03-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0011_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='l_postid',
            field=models.IntegerField(default=0),
        ),
    ]
