# Generated by Django 3.1.2 on 2021-03-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inno_user', '0012_auto_20210307_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='l_user',
            field=models.CharField(default='prem', max_length=20),
        ),
    ]
