# Generated by Django 3.1.2 on 2020-10-19 13:40

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='photos')),
                ('desc', models.TextField(max_length=builtins.max)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
